@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2MmMyMGE4LTY4MmMtNGM0Ni1iMWE1LTRlMjY1NTZmMjIzZiIsInJvbGUiOiJhZG1pbiIsImp0aSI6ImFlTE5EUHM0WksiLCJpYXQiOjE2MjY4ODU3NDcsImV4cCI6MTYyNjg5Mjk0N30.A-FFR2G1j59-a89ZwxSBUDCmnE1rexvASnSkNpw17mQ
@hostname2=http://127.0.0.1:3000/api
@hostname=http://188.126.44.111/api

###
POST {{hostname}}/user/login
Content-Type: application/json

{
    "email":"rezaian-n@rudn.ru",
    "password":"1234"
}


###
GET http://127.0.0.1:3000/user/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwianRpIjoiREVPcWRRc09MTyIsImlhdCI6MTYxOTkwNTAyMn0.vH97HCNHB7ApJ7QPHmnuNYj6o1fKxDf3VQenke8XRGs

###
GET http://127.0.0.1:3000/api/Profile/04faadb9-a27e-4e31-bbd9-82abfc3f1e46
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI2ZDA2MWNkLTUyNDQtNGE1YS1hNTIzLWRkOWZiNmQwNWZkNyIsInJvbGUiOiJzdHVkZW50IiwianRpIjoiV1lGNjdCVHJESCIsImlhdCI6MTYxOTk1NTA3OH0.-fAYDbTnP5uaU5VK0MP6g79F30WUsNIIQSsH147GWCs
###
GET http://188.126.44.111/api/Profile/Teachers/0/0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU1NTI4Y2YxLTllMjEtNDQ5ZS04OWMyLTk5OGIyOWUzZjI3MiIsInJvbGUiOiJhZG1pbiIsImp0aSI6ImhSYmo3QVFVem4iLCJpYXQiOjE2MTk5NTY1MjR9.6pTH4VDljTLsdRw4CfxsIQOsuHhwVqzJ8LOs6vE_ZX0


###
DELETE http://127.0.0.1:3000/Profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6IjEiLCJqdGkiOiJybkViblpBNHlJIiwiaWF0IjoxNjE5NjE1MjMxfQ.LkpRMyPm5hL34J_GFC1WI0S3V0T5m6uwTgJrPhZlj0E

{
    "Items":[2]
}

###
PUT http://127.0.0.1:3000/Profile/11
Content-Type: application/json

{
    "Name" : "naeimre",
    "Email" : "naeim@naeim.ru"
}

###
POST http://127.0.0.1:3000/Api/Profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4NDJjOTdiLTEzMDctNDg4YS1iZDJjLWY3ZDg2MDQzODA0MiIsInJvbGUiOiJhZG1pbiIsImp0aSI6InBUcUJzaDNCdnUiLCJpYXQiOjE2MjAxNDA0NDJ9.aLfzFcJxfY2jw_oM8LWH2znhzWQEqOI6R55M6t5kYVo

{
    "Name" : "user100",
    "Birthday" : "2000-04-21",
    "Sex" : 1,
    "Email" : "user100@rudn.ru",
    "Phone" : "9252706166",
    "Address" : "Prospect mira ava 70",
    "Country" : "Russia",
    "City" : "Moscoww",
    "FacultyId" : 1,
    "DepartmentId" : "2",
    "FieldId" : "3",
    "TypeStudy" : 4,
    "FormStudy" : 5,
    "YearStudy" : 6,
    "Additional" : "test",
    "Photo" : "photo",
    "Access" : "student",
    "Status" : 1,
    "Password1":"$10$cPeqphlqybcfvCQYKz5L1ORLcQKMsRdQqZvnnDurgmZ613oajjct6"
}


###
PUT http://127.0.0.1:3000/Profile/46
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDYsInJvbGUiOiJzdHVkZW50IiwianRpIjoiMTBSSWlJNllLNiIsImlhdCI6MTYxOTkwNzU0MH0.pjPl4xzw3dRV-akqPhvmgNHugoVnROYdg7UnrZDvu5E

{
    "Name" : "naeeeeim  ",
    "Birthday" : "2000-04-21",
    "Sex" : 1,
    "Email" : "na@eimq.ru",
    "Phone" : "9252706166",
    "Address" : "msocow",
    "Country" : "russia",
    "City" : "moscow",
    "FacultyId" : 1,
    "DepartmentId" : "2",
    "FieldId" : "3",
    "TypeStudy" : 4,
    "FormStudy" : 5,
    "YearStudy" : 6,
    "Additional" : "test",
    "Photo" : "photo",
    "Access" : "student",
    "Status" : 1
}



###
GET {{hostname}}/SubjectUser/3
Content-Type: application/json
Authorization: Bearer {{token}}

###
### /Filter/:subjectid/:offset/:limit
GET {{hostname}}/SubjectUser/Filter/0/0/0
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{hostname}}/SubjectUser
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "dataArray":[{"userId":"0a1d1bda-c674-4a2b-b6d6-82022c3779b8","subjectId":"4"},{"userId":"0a1d1bda-c674-4a2b-b6d6-82022c3779b8","subjectId":"3"}]
   
}



###
GET {{hostname}}/Faculty/0/0/0
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{hostname}}/Department/Filter/0/0/0
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET {{hostname2}}/Field/Filter/1/0/0/0/0
Content-Type: application/json
Authorization: Bearer {{token}}

###
#/:groupid/:userid/:yearstudy/:facultyid/:departmentid/:fieldid/:subjectid/:offset/:limit
GET {{hostname}}/GroupRelation/Filter/0/0/0/0/0/0/0/0/0
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{hostname}}/GroupStudent/Filter/0/0/0/0
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{hostname2}}/Question/Filter/0/0/0/0
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{hostname2}}/Question/2
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{hostname2}}/Question
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "userId":"108e5270-91ee-471b-adfc-b874992794b1",
 "subjectId":2,
 "questionContent":"aaa3",
 "questionType":1,
 "questionScore":5,
 "model":1,
 "status" :1,
"answers":[{"answerContent":"q1","answerCorrect":true},{"answerContent":"q2","answerCorrect":false}]
}


###
PUT {{hostname2}}/User/Status/fe7fbe6b-1701-47e7-b23d-a4a9fefbf225
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status":2
}


###
#/Filter/:relationId
GET {{hostname}}/SubGroupStudent/Filter/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{hostname}}/SubGroupStudent/Filter/List/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{hostname}}/SubGroupStudent
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "dataArray":[{"userId":"c0a7934d-bfbc-40ff-bb2f-4fdec014ad8c","subgroupId":"3"},{"userId":"b7bf08b7-87a5-4dfd-b240-1ad9710f3dfd","subgroupId":"2"}]
}

###
DELETE {{hostname2}}/SubGroup
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "items":[2]
}

###
DELETE {{hostname2}}/SubGroupStudent
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "items":[2]
}



###
GET {{hostname2}}/Permission
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{hostname2}}/Permission
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title":"test11",
    "tag":"tag11"
}



###
PUT {{hostname2}}/Permission/11
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title":"test11",
    "tag":"tag 11"
}


###
DELETE {{hostname2}}/Permission
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "items":[11]
}



###
GET {{hostname2}}/PermissionUser/962c20a8-682c-4c46-b1a5-4e26556f223f
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{hostname2}}/PermissionUser
Content-Type: application/json
Authorization: Bearer {{token}}

{
    
    "dataArray":[
        {"userId":"c0a7934d-bfbc-40ff-bb2f-4fdec014ad8c","permissionId":"1","access":"0"}
        , {"userId":"c0a7934d-bfbc-40ff-bb2f-4fdec014ad8c","permissionId":"2","access":"1"}
        , {"userId":"c0a7934d-bfbc-40ff-bb2f-4fdec014ad8c","permissionId":"3","access":"1"}
        , {"userId":"c0a7934d-bfbc-40ff-bb2f-4fdec014ad8c","permissionId":"4","access":"1"}
      
    ]
}


###
DELETE {{hostname2}}/PermissionUser
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "items":["c0a7934d-bfbc-40ff-bb2f-4fdec014ad8c"]
}


###
PUT {{hostname2}}/PermissionUser/c0a7934d-bfbc-40ff-bb2f-4fdec014ad8c1
Content-Type: application/json
Authorization: Bearer {{token}}

{
"dataArray":[
         {"permissionId":"1","access":"0"}
        , {"permissionId":"2","access":"0"}
        , {"permissionId":"3","access":"0"}
        , {"permissionId":"4","access":"0"}
      
    ]
}


####
GET {{hostname2}}/User/6ebd5269-1f59-4cfe-bdef-53c90e8cf1d7
Content-Type: application/json
Authorization: Bearer {{token}}


####
PUT {{hostname2}}/User/6ebd5269-1f59-4cfe-bdef-53c90e8cf1d7
Content-Type: application/json
Authorization: Bearer {{token}}

{
"id":"6ebd5269-1f59-4cfe-bdef-53c90e8cf1d7",
"name":"Ширяев Юстин Игнатьевич",
"birthday":"1981-12-12",
"sex":true,
"email":"user43@rudn.ru",
"phone":"+79212679113",
"address":"ул. Хрущёва, дом 67",
"country":"Россия",
"city":"Москва",
"fieldId":1,
"typeStudy":0,
"yearStudy":"2019-2020",
"additional":"desc1",
"photo":"file",
"access":"teacher",
"status":0,
"password":"$2a$10$99Zklk7LjrNiQnqVk6P3tOcz9pSuX7JslGfAgsDP3n3VkuClpqxaq"
}

###
POST {{hostname2}}/User
Content-Type: application/json
Authorization: Bearer {{token}}

{"id":"",
"name":"mazhar admin",
"birthday":"2021-07-21",
"sex":false,
"email":"a23@rudn.ru",
"phone":"09186882744",
"address":"kermanshah",
"country":"IR-ИСЛАМСКАЯ РЕСПУБЛИКА ИРАН (ИРАН)",
"city":"kermanshah",
"facultyId":0,
"facultyTitle":"",
"departmentId":0,
"departmentTitle":"",
"fieldId":null,
"fieldTitle":"",
"typeStudy":0,
"yearStudy":"2020-2021",
"additional":"desc 1",
"photo":"1efe472080f1a17de888f91abb31e60b83ae.jpg",
"access":"admin",
"status":1,
"password":"1234"}
